<footer>
    <nav>
        <ul>
            <li><a href="/res04-projet-soutenance/confidentiality">Confidentiality</a></li>
            <li><a href="/res04-projet-soutenance/credits">Credits</a></li>
            <li><a href="/res04-projet-soutenance/legal-notices">Legal notices</a></li>
            <li><a href="mailto:marie.richir35@gmail.com">Contact</a></li>
        </ul>
    </nav>
    <p>Website created by Marie Richir, fonts taken on <a href="https://fonts.google.com/" target="_blank">Google Font</a>.</p>
</footer>