<header>
    <h1 class="hidden">Farming Companion</h1>
    <img src="/res04-projet-soutenance/assets/images/logo-fc.png" alt="Logo of Farming Companion">
    <nav>
        <ul>
            <li><a href="/res04-projet-soutenance/">Homepage</a></li>
            <li><a href="/res04-projet-soutenance/villagers">Villagers</a></li>

            <?php
            if(!isset($_SESSION['user']) && !isset($_SESSION['admin']))
            {
                echo '
                <li><a href="/res04-projet-soutenance/register">Register</a></li>
                <li><a href="/res04-projet-soutenance/login">Login</a></li>';
            }
            ?>
            
            <?php
            // var_dump($_SESSION['user']);
            if(isset($_SESSION['user']) || isset($_SESSION['admin']))
            {
                echo "<li><a href='/res04-projet-soutenance/my-account'>My account</a></li>
                    <li><a href='/res04-projet-soutenance/my-games'>My games</a></li>";
            }
            else if(isset($_SESSION['admin']))
            {
                echo "<li><a href='/res04-projet-soutenance/admin'>Admin Dashboard</a></li>";
            }
            ?>
            
            <?php
            if(isset($_SESSION['user']) || isset($_SESSION['admin']))
            {
            ?>
            <li>
                <form method="POST" action="/res04-projet-soutenance/logout">
                    <input type="submit" name="logout" id="logout" value="">
                </form>
            </li>
            <?php
                }
            ?>
            <li>
                <button class="dark"></button>
            </li>
        </ul>
    </nav>
    <div class="font-size">
        <button>A</button>
        <button>A</button>
    </div>
</header>