<header>
    <h1>Farming Companion</h1>
    <nav>
        <ul>
            <li><a href="/res04-projet-soutenance/">Homepage</a></li>
            <li><a href="/res04-projet-soutenance/villagers">Villagers</a></li>
            <li><a href="/res04-projet-soutenance/register">Register</a></li>
            <li><a href="/res04-projet-soutenance/login">Login</a></li>
            <?php
            // var_dump($_SESSION['user']);
            if(isset($_SESSION['user']))
            {
                echo "<li><a href='/res04-projet-soutenance/my-account'>My account</a></li>";
                echo "<li><a href='/res04-projet-soutenance/my-games'>My games</a></li>";
            }
            else if(isset($_SESSION['admin']))
            {
                echo "<li><a href='/res04-projet-soutenance/admin'>Admin Dashboard</a></li>";
            }
            ?>
            
        </ul>
    </nav>
    <?php
        if(isset($_SESSION['user']) || isset($_SESSION['admin']))
        {
    ?>
    <form method="POST" action="/res04-projet-soutenance/logout">
        <input type="submit" name="logout" id="logout" value="logout">
    </form>
    <?php
        }
    ?>
</header>