<header>
    <h1>Farming Companion</h1>
    <nav>
        <ul>
            <li><a href="index.php?route=homepage">Homepage</a></li>
            <li><a href="index.php?route=villagers">Villagers</a></li>
            <li><a href="index.php?route=register">Register</a></li>
            <li><a href="index.php?route=login">Login</a></li>
            <?php
            // var_dump($_SESSION['user']);
            if(isset($_SESSION['user']))
            {
                echo "<li><a href='index.php?route=my-account'>My account</a></li>";
                echo "<li><a href='index.php?route=my-games'>My games</a></li>";
            }
            else if(isset($_SESSION['admin']))
            {
                echo "<li><a href='index.php?route=admin'>Admin Dashboard</a></li>";
            }
            ?>
            
        </ul>
    </nav>
    <?php
        if(isset($_SESSION['user']) || isset($_SESSION['admin']))
        {
    ?>
    <form method="POST" action="index.php?route=logout">
        <input type="submit" name="logout" id="logout" value="logout">
    </form>
    <?php
        }
    ?>
</header>