<header class="admin-header">
    <h1>Admin Dashboard</h1>

    <?php
        if(isset($_SESSION['admin']))
        {
    ?>
    <form method="POST" action="/res04-projet-soutenance/logout">
        <input type="submit" name="logout" id="logout" value="Logout">
    </form>
    <?php
        }
    ?>
    
    <nav>
        <ul>
            <li><a href="/res04-projet-soutenance/">Back to the farming</a></li>
            <li><a href="/res04-projet-soutenance/admin">Home of the Admin</a></li>
            <li><a href="/res04-projet-soutenance/admin/all-users">All users</a></li>
            <li><a href="/res04-projet-soutenance/admin/all-saved-games">All saved games</a></li>
            <li><a href="/res04-projet-soutenance/admin/statistics">Statistics</a></li>
            <li><a href="/res04-projet-soutenance/admin/edit">Edit admin account</a></li>
        </ul>
    </nav>
</header>