<main class="all-users">
    <h2>All users</h2>

    <input type="search" id="search" name="search" placeholder="Search for a user" class="search-user">

    <table>
        <thead>
            <tr>
                <th>Username</th>
                <th>Email</th>
                <th>Role</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php
                foreach($data as $user)
                {
                    echo 
                        "<tr class='data'>
                            <td class='data-row'>".$user->getUsername()."</td>
                            <td>".$user->getEmail()."</td>
                            <td>".$user->getRole()->getName()."</td>";
                            if($user->getRole()->getName() === 'user')
                            {
                            echo 
                                "<td>
                                    <form action='/res04-projet-soutenance/admin/all-users' method='POST'>
                                        <input type='hidden' name='user_id' id='user_id' value='".$user->getId()."'>
                                        <input type='submit' name='submit-delete-account-admin' id='submit-delete-account-admin' value='Delete'>
                                    </form>
                                    <form action='/res04-projet-soutenance/admin/all-users' method='POST' id='edit-the-role'>
                                        <input type='hidden' name='user_to_edit_id' id='user_to_edit_id' value='".$user->getId()."'>
                                        <input type='hidden' name='user_role_id' id='user_role_id' value='1'>
                                        <input type='submit' name='submit-change-role' id='submit-change-role' value='Change to admin'>
                                    </form>
                                </td>";
                            }
                        "</tr>";
                }
            ?>
        </tbody>
        <tfoot>
            <tr>
                <td colspan=4>
                    <?php
                        echo "Total users : ".count($data);
                    ?>
                </td>
            </tr>
        </tfoot>
    </table>
</main>