<h3>All users</h3>
<table>
    <thead>
        <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Role</th>
        </tr>
    </thead>
    <tbody>
        <?php
            foreach($data as $user)
            {
                echo 
                    "<tr>
                        <td>".$user->getUsername()."</td>
                        <td>".$user->getEmail()."</td>
                        <td>".$user->getRole()->getName()."</td>
                    </tr>";
            }
        ?>
    </tbody>
    <tfoot>
        <tr>
            <td rowspan=3>
                <?php
                    echo "Total users : ".count($data);
                ?>
            </td>
        </tr>
    </tfoot>
</table>