<section>
    <h3>Schedule</h3>
    <p>
        <?php
            foreach($_SESSION['planning']->getSchedule() as $key => $days)
            {
                // put condition if marriage, make another loop
                echo $key;
                if($key !== "Marriage")
                {
                    // echo $key;
                    foreach($days as $clef => $time)
                    {
                        echo $clef.' '.$time;
                    }
                }
                else
                {
                    foreach($days as $clef => $time)
                    {
                        
                    }
                }
            }
        ?>
    </p>
</section>