<h3 class="title"><button>Schedule</button></h3>
<table class="events">
    <?php
        foreach($_SESSION['planning']->getSchedule() as $key => $days)
        {
            // put condition if marriage, make another loop
            echo '<tr><th>'.$key.'</th></tr>';
            if($key !== "Marriage")
            {
                // echo '<tr><td>'.$key.'</td></tr>';
                foreach($days as $clef => $time)
                {
                    foreach($time as $keys => $hours)
                    {
                        echo '<tr><td>'.$keys.': '.$hours.'</td></tr>';
                    }
                }
            }
            else
            {
                foreach($days as $clef => $time)
                {
                    echo '<tr><td>'.$clef.'</td></tr>';
                    foreach($time as $clefs => $location)
                    {
                        foreach($location as $name => $do)
                        {
                            echo '<tr><td>'.$name.' '.$do.'</td></tr>';
                        }
                    }
                }
            }
        }
    ?>
</table>