<h3 class="title">Schedule</h3>
<article class="events">
    <?php
        foreach($_SESSION['planning']->getSchedule() as $key => $schedules)
        {
            echo '<table>
                    <thead>
                        <tr>
                            <th colspan=2><button class="title">'.$key.'</button></th>
                        </tr>
                    </thead>
                    <tbody class="events">';
            foreach($schedules as $clé => $schedule)
            {
                echo '<tr>';
                foreach($schedule as $keyz => $planning)
                {
                    echo '<td>'.$keyz. ': ' .$planning.'</td>';
                }
                echo '</tr>';
            }
            echo '</tbody></table>';
        }
    ?>
</article>