<h3 class="title">Schedule</h3>
<section class="events">
    <h4 class="hidden">Schedule organised in tables</h4>
    <?php
        foreach($_SESSION['planning']->getSchedule() as $key => $schedules)
        {
            echo '<table>
                    <thead>
                        <tr>
                            <th colspan=2><button class="title">'.$key.'</button></th>
                        </tr>
                    </thead>
                    <tbody class="events">';
            foreach($schedules as $keys => $schedule)
            {
                echo '<tr>
                        <td class="day" colspan=2>'.$keys.'</td>
                    </tr>';
                foreach($schedule as $keyz => $planning)
                {
                    echo '<tr>';
                    foreach($planning as $cle => $plan)
                    {
                        echo "<td>".$cle.": ".$plan."</td>";
                    }
                    echo '</tr>';
                }
            }
            echo '</tbody></table>';
        }
    ?>
</section>