<h3 class="title"><button>Schedule</button></h3>
<table class="events">
    <?php
        foreach($_SESSION['planning']->getSchedule() as $key => $schedules)
        {
            echo '<tr><th>'.$key.'</th></tr>';
            foreach($schedules as $clé => $schedule)
            {
                // echo $keys;
                foreach($schedule as $keyz => $planning)
                {
                    echo '<tr><td>'.$keyz. ' ' .$planning.'</td></tr>';
                }
            }
        }
    ?>
</table>