<?php
    $villagers = $data;
?>

<main class="all-villagers">
    <h2>Villagers</h2>

    <input type="search" id="search" name="search" placeholder="Search for a villager" class="search">

    <article class="villagers">
        <h3 class="hidden">All the villagers</h3>
        <ul>
        <?php
            foreach($villagers as $villager)
            {
        ?>

        <li class="data-row">
            <img src="<?= $villager->getPicture()->getUrl() ;?>" alt="<?= $villager->getPicture()->getAlt();?>">
            <a href="/res04-projet-soutenance/villagers/<?= $villager->getId();?>"><?= $villager->getName();?></a>
        </li>

        <?php        
            }
        ?>
        </ul>
    </article>
</main>