<main>
    <?php
    $villager = $_SESSION['villager'];
    // var_dump($_SESSION['villager']);
    ?>
    <h2><?= $villager->getName() ;?></h2>
    <img src="<?= $villager->getPicture()->getUrl() ;?>" alt="<?= $villager->getPicture()->getAlt() ;?>">

    <section>
        <p>Birthday : <?= $villager->getBirthday() ;?></p>
        <p>Can you date them ? 
            <?php 
                if(intval($villager->getIsDatable()) === 1)
                {
                    echo "Yes";
                }
                else
                {
                    echo "No";
                }
            ?>
        </p>
        <!-- Display all the informations of a villager -->
    </section>
    <section>
        <h3>Events</h3>
        <table>
            <?php
                // var_dump($villager->getEvents());
                foreach($villager->getEvents() as $key => $event)
                {
                    echo "<tr><td>$key</td><td>$event</td></tr>";
                }
            ?>
        </table>
    </section>
    <section>
        <h3>Gifts</h3>
        <table>
            <tr>
                <th>Loves</th>
                <td>
                    <?php 
                        foreach($villager->getLove() as $love)
                        {
                            echo $love . ', ';
                        }
                    ?>
                </td>
            </tr>
            <tr>
                <th>Likes</th>
                <td>
                    <?php 
                        foreach($villager->getLike() as $like)
                        {
                            echo $like . ', ';
                        }
                    ?>
                </td>
            </tr>
            <tr>
                <th>Neutral</th>
                <td>
                    <?php 
                        foreach($villager->getNeutral() as $neutral)
                        {
                            echo $neutral . ', ';
                        }
                    ?>
                </td>
            </tr>
            <tr>
                <th>Dislikes</th>
                <td>
                    <?php 
                        foreach($villager->getDislike() as $dislike)
                        {
                            echo $dislike . ', ';
                        }
                    ?>
                </td>
            </tr>
            <tr>
                <th>Hates</th>
                <td>
                    <?php 
                        foreach($villager->getHate() as $hate)
                        {
                            echo $hate . ', ';
                        }
                    ?>
                </td>
            </tr>
        </table>
    </section>
    <section>
        <h3>Schedule</h3>
        <p>
            <?php
                foreach($_SESSION['planning']->getSchedule() as $key => $schedules)
                {
                    echo $key;
                    foreach($schedules as $keys => $schedule)
                    {
                        echo $keys;
                        foreach($schedule as $keyz => $planning)
                        {
                            // echo $keyz;
                            foreach($planning as $key => $plan)
                            {
                                echo $key. ' ' .$plan;
                            }
                        }
                    }
                }
            ?>
        </p>
    </section>
</main>