
<?php
// var_dump($data);
    $villager = $data[0];
?>

<main class="villager">
    <h2><?= $villager->getName() ;?></h2>

    <article class="single-villager">
        <img src="/res04-projet-soutenance/<?= $villager->getPicture()->getUrl() ;?>" alt="<?= $villager->getPicture()->getAlt() ;?>" class="villager-picture">

        <section id="general" class="villager-general">
            <p>Birthday : <?= $villager->getBirthday() ;?></p>
            <p>Can you date them ? 
                <?php 
                    if(intval($villager->getIsDatable()) === 1)
                    {
                        echo "Yes";
                    }
                    else
                    {
                        echo "No";
                    }
                ?>
            </p>
        </section>

        <section id="events" class="villager-events">
            <h3><button>Events</button></h3>
            <table>
                <?php
                    // var_dump($villager->getEvents());
                    foreach($villager->getEvents() as $key => $event)
                    {
                        echo "<tr>
                                <th>$key</th>
                            </tr>
                            <tr>
                                <td>$event</td>
                            </tr>";
                    }
                ?>
            </table>
        </section>

        <section id="gifts" class="gifts">
            <h3><button>Gifts</button></h3>
            <table>
                <tr>
                    <th>Loves</th>
                </tr>
                <tr>
                    <td>
                        <?php 
                            $loves = count($villager->getLove());
                            foreach($villager->getLove() as $key => $love)
                            {
                                echo $love;
                                if($key < $loves - 1)
                                {
                                    echo ', ';
                                }
                                else
                                {
                                    echo '.'; // For the last one, i wanted a dot instead of a comma
                                }
                            }
                        ?>
                    </td>
                </tr>

                <tr>
                    <th>Likes</th>
                </tr>
                <tr>
                    <td>
                        <?php 
                            foreach($villager->getLike() as $like)
                            {
                                echo $like . ', ';
                            }
                        ?>
                    </td>
                </tr>

                <tr>
                    <th>Neutral</th>
                </tr>
                <tr>
                    <td>
                        <?php 
                            foreach($villager->getNeutral() as $neutral)
                            {
                                echo $neutral . ', ';
                            }
                        ?>
                    </td>
                </tr>

                <tr>
                    <th>Dislikes</th>
                </tr>
                <tr>
                    <td>
                        <?php 
                            foreach($villager->getDislike() as $dislike)
                            {
                                echo $dislike . ', ';
                            }
                        ?>
                    </td>
                </tr>

                <tr>
                    <th>Hates</th>
                </tr>
                <tr>
                    <td>
                        <?php 
                            foreach($villager->getHate() as $hate)
                            {
                                echo $hate . ', ';
                            }
                        ?>
                    </td>
                </tr>
            </table>
        </section>

        <section id="planning" class="planning">
            <?php
                // I had to make a condition because everyone's planning didn't match for the loops
                if($villager->getName() === "Caroline" ||
                    $villager->getName() === "Clint" ||
                    $villager->getName() === "Evelyn" ||
                    $villager->getName() === "George" ||
                    $villager->getName() === "Gus" ||
                    $villager->getName() === "Jas" ||
                    $villager->getName() === "Kent" ||
                    $villager->getName() === "Linus" ||
                    $villager->getName() === "Marnie" ||
                    $villager->getName() === "Pam" ||
                    $villager->getName() === "Pierre" ||
                    $villager->getName() === "Robin" ||
                    $villager->getName() === "Sandy" ||
                    $villager->getName() === "Vincent" ||
                    $villager->getName() === "Willy")
                {
                    require 'partials/_planning2.phtml';
                }
                else if($villager->getName() === "Dwarf" ||
                        $villager->getName() === "Krobus" ||
                        $villager->getName() === "Wizard")
                {
                    require 'partials/_planning1.phtml';
                }
                else if($villager->getName() === "Emily")
                {
                    require 'partials/_emily.phtml';
                }
                else
                {
                    require 'partials/_planning3.phtml';
                }
            ?>
        </section>
    </article>
</main>
