<article id="bundles" class="bundles">
    <?php
        $player = $data['bundles'];
    ?>
    <h3 class="title">Bundles</h3>
    <section class="events">
        <ul>
            <?php
                foreach($player as $bundle)
                {
            ?>
            <li>
                <img src="/res04-projet-soutenance/assets/images/<?= $bundle->getBundleName(); ?>.png" alt="Picture of a bundle" />
                <p><?=$bundle->getBundleName();?>: 
                <?php 
                    if($bundle->getComplete() === true)
                    {
                        echo " <span class='green'>Completed</span>";
                    }
                    else
                    {
                        echo " <span class='pink'>Not completed</span>";
                    }
                ?>
                </p>
            </li>
            <?php
                }
            ?>
        </ul>
    </section>
</article>