<?php
    if($key === "bundles")
    {
?>
<h3 class="title"><button>Bundles of the Community Center</button></h3>
<ul class="events">
    <?php
        foreach($player as $bundle)
        {
    ?>
    <li><?=$bundle->getBundleName();?>: 
        <?php 
            if($bundle->getComplete() === true)
            {
                echo " Completed";
            }
            else
            {
                echo " Not completed";
            }
        ?>
    </li>
    <?php
        }
    }
    ?>
</ul>