<article class="locations">
    <?php
        $player = $data['locations'];
    ?>
    <h3 class="title">Locations discovered</h3>
    <dl class="events">
        <?php
            foreach($player as $locations)
            {
                if($locations->getIsDiscovered() ===  true)
                {
                    echo "<dt>".$locations->getName()."</dt>
                    <dd> has been discovered.</dd>";
                }
                else
                {
                    echo "<dt>".$locations->getName()."</dt>
                    <dd> has not been discovered yet.</dd>";
                }
            }
        ?>
    </dl>
</article>