<article id="artifacts" class="artifacts">
    <?php
        $player = $data['items'];
    ?>
    <h3 class="title">Artifacts</h3>
    <section class="events">
        <h4>Donated to the museum</h4> 
        <ul>
            <?php
                foreach($player as $museum)
                {
                    if($museum->getHas() ===  true)
                    {
            ?>
                        <?php
                        foreach($data['itemsPictures'] as $item)
                        {
                            if($item->getName() === $museum->getName())
                            {
                        ?>
                        <li>
                            <img src="/res04-projet-soutenance/<?=$item->getPicture()->getUrl();?>" alt="<?=$item->getPicture()->getAlt();?>">
                            <p><?=$museum->getName();?></p>
                        </li>
                            <?php
                            }
                        }
                    }
                }
            ?>
        </ul>
        <h4>Not found yet</h4>
        <ul>
            <?php
                foreach($player as $museum)
                {
                    if($museum->getHas() ===  false)
                    {
                        ?>
                        <?php
                        foreach($data['itemsPictures'] as $item)
                        {
                            if($item->getName() === $museum->getName())
                            {
                        ?>
                        <li>
                            <img src="/res04-projet-soutenance/<?=$item->getPicture()->getUrl();?>" alt="<?=$item->getPicture()->getAlt();?>">
                            <p><?=$museum->getName();?></p>
                        </li>
                            <?php
                            }
                        }
                    }
                }
            ?>
        </ul>
    </section>
</article>