<article id="relationships" class="relationships">
    <?php
        $player = $data['relationships'];
    ?>
    <h3 class="title">Relationships</h3>
    <section class="events">
        <ul>
            <?php
                foreach($player as $relationship)
                {
            ?>
                    <li>
                        <a href='/res04-projet-soutenance/villagers/<?= $relationship->getVillager()->getId();?>'>
                            <!-- <?=$relationship->getVillager()->getName();?> -->
                            <img src="/res04-projet-soutenance/<?=$relationship->getVillager()->getPicture()->getUrl();?>" alt="<?=$relationship->getVillager()->getPicture()->getAlt();?>">
                        </a>
                        <p><span><?=intval($relationship->getLevel() / 250);?></span> heart(s) out of 10.</p>
                    </li>
            <?php
                }
            ?>
        </ul>
    </section>
</article>