<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- <link href="assets/styles/scss/style.css" rel="stylesheet"> -->
        <title>Farming Companion</title>
    </head>
    <body>
        <?php
            require 'partials/_header.phtml';
            require $template;
            require 'partials/_footer.phtml';
        ?>
    </body>
</html>