<form method="POST" action="/res04-projet-soutenance/register">
    <fieldset>
        <label for="username">Username</label>
        <input type="text" name="username" id="username">
    </fieldset>
    <fieldset>
        <label for="email">Email</label>
        <input type="email" name="email" id="email">
    </fieldset>
    <fieldset>
        <label for="password">Password</label>
        <input type="password" name="password" id="password">
    </fieldset>
    <fieldset>
        <label for="confirm-password">Confirm the password</label>
        <input type="password" name="confirm-password" id="confirm-password">
    </fieldset>

    <input type="submit" name="submit-new-user" id="submit-new-user" value="Register">
</form>