<main>
    <h2>Edit my informations</h2>

    <form action="/res04-projet-soutenance/my-account/edit" method="POST" class="forms" id="edit-user-form">
        <fieldset>
            <label for="new-user-username">New username</label>
            <input type="text" name="new-user-username" id="new-user-username">
            <p class="errorUsername"></p>
        </fieldset>
        <fieldset>
            <label for="new-user-email">New email</label>
            <input type="text" name="new-user-email" id="new-user-email">
            <p class="errorEmail"></p>
        </fieldset>
        <fieldset>
            <label for="new-user-password">New password</label>
            <input type="password" name="new-user-password" id="new-user-password">
            <p class="errorPassword"></p>
        </fieldset>
        <fieldset>
            <label for="confirm-new-user-password">Confirm your password</label>
            <input type="password" name="confirm-new-user-password" id="confirm-new-user-password">
            <p class="errorConfirmPassword"></p>
        </fieldset>

        <input type="submit" value="Confirm" name="submit-edit-user" id="submit-edit-user">
    </form>
</main>