<main class="player-progress">
    <div class="accessibility" aria-description="accessibility menu">
        <a href="#player">Player</a>
        <a href="#skills">Skills</a>
        <a href="#equipment">Equipment</a>
        <a href="#books">Books</a>
        <a href="#statistics">Statistics</a>
        <a href="#bundles">Bundles</a>
        <a href="#artifacts">Artifacts</a>
        <a href="#relationships">Relationships</a>
        <a href="#locations">Locations</a>
    </div>

    <h2>Your farm</h2>
    <?php
        require 'game_partials/_player.phtml'; 
        require 'game_partials/_skills.phtml'; 
        require 'game_partials/_bundles.phtml'; 
        require 'game_partials/_museumItems.phtml'; 
        require 'game_partials/_books.phtml';
        require 'game_partials/_relationships.phtml';
        require 'game_partials/_locations.phtml';
        require 'game_partials/_possessedItems.phtml';
        require 'game_partials/_stats.phtml'; 
    ?>
</main>

