<main>
    <h2>Login</h2>
    <form method="POST" action="/res04-projet-soutenance/login" id="login-form" class="register-login-edit">
        <fieldset>
            <label for="username">Username</label>
            <input type="text" name="username" id="username">
        </fieldset>
        <fieldset>
            <label for="password">Password</label>
            <input type="password" name="password" id="password">
        </fieldset>
        <p id="error"></p>

        <input type="submit" name="login" id="login" value="Login">
    </form>
</main>