<main>
    <h2>Login</h2>
    <form method="POST" action="/res04-projet-soutenance/login" id="login-form" class="forms">
        <fieldset>
            <label for="username">Username</label>
            <input type="text" name="username" id="username">
        </fieldset>
        <fieldset>
            <label for="password">Password</label>
            <input type="password" name="password" id="password">
        </fieldset>
        <p class="error" id="error"></p>

        <a href="/res04-projet-soutenance/register" class="pink">Go register</a>
        <input type="submit" name="login" id="login" value="Login">
    </form>
</main>