<main>
    <?php
        $user = $data["user"];
    ?>

    <h2>Hello <?=$user->getUsername();?></h2>

    <section class="account">
        <h3>My informations</h3>
        <dl>
            <dt>Username</dt>
            <dd><?=$user->getUsername();?></dd>

            <dt>Email</dt>
            <dd><?=$user->getEmail();?></dd>

            <dt>Registration date</dt>
            <dd><?=$user->getRegistrationDate();?></dd>
        </dl>

        <a href="/res04-projet-soutenance/my-account/edit">Edit my informations</a>
        <a href="/res04-projet-soutenance/my-account/delete">Delete my account</a>
    </section>
</main>
