<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="title" content="Farming Companion">
        <meta name="description" content="A tracker to a Stardew Valley game">
        <meta name="author" content="Marie">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Chakra+Petch&family=Exo+2:wght@300&display=swap" rel="stylesheet">
        <!-- <link href="assets/styles/css/style.css" rel="stylesheet"> -->
        <title>Farming Companion</title>
    </head>
    <body>
        <?php
            require 'partials/_header.phtml';
        ?>
        <main>
        <?php
            require $template;
        ?>
        </main>
        <?php
            require 'partials/_footer.phtml';
        ?>

        <script type="module" src="/res04-projet-soutenance/assets/js/index.js"></script>
    </body>
</html>