<main>
    <h2>Add informations to the tutorial</h2>

    <form action="" method="">
        <fieldset>
            <label for="add-title">Title of the section</label>
            <input type="text" name="add-title" id="add-title">
        </fieldset>
        <fieldset>
            <label for="add-text">Text</label>
            <textarea id="add-text" name="add-text"></textarea>
        </fieldset>
    </form>
</main>